# ─── i18n ───

LANG = {
    "en": {
        "banner_title": "ClaudePetRebirth",
        "banner_sub": "Roll your Claude Code companion pet!",
        "roll": "Roll",
        "rarity": "Rarity",
        "eyes": "Eyes",
        "hat": "Hat",
        "stats": "Stats",
        "commands": "Commands",
        "cmd_reroll": "Reroll a new random pet",
        "cmd_keep": "Keep this pet (add to favorites)",
        "cmd_favs": "View favorites",
        "cmd_remove": "Remove last favorite",
        "cmd_save": "Save favorites to file",
        "cmd_anim": "Toggle animation preview",
        "cmd_help": "Show this help",
        "cmd_lang": "Switch language",
        "cmd_quit": "Quit",
        "no_favs": "No favorites yet! Press [k] to keep a pet.",
        "favs_title": "Favorites",
        "fav_apply": "Apply that pet to Claude Code",
        "fav_remove": "Remove last favorite",
        "fav_back": "Go back",
        "fav_invalid": "Invalid number. Choose",
        "kept": "Kept",
        "favs_total": "favorites total",
        "removed": "Removed",
        "from_favs": "from favorites.",
        "no_favs_remove": "No favorites to remove.",
        "saved": "Saved",
        "favs_to": "favorites to",
        "no_favs_save": "No favorites to save.",
        "anim": "Animation",
        "press_enter": "Press Enter to continue...",
        "apply_title": "Applying pet to Claude Code",
        "apply_target": "Target",
        "apply_searching": "Searching for matching salt...",
        "apply_found": "Found in",
        "apply_attempts": "attempts",
        "apply_patched": "Patched!",
        "apply_replacements": "replacements, verified",
        "apply_backup": "Backup",
        "apply_patch_failed": "Patch failed",
        "apply_confirm": "Apply this pet to Claude Code? [y/N]",
        "apply_name": "Give your {species} a name",
        "apply_set": "Companion set",
        "apply_personality": "Personality",
        "apply_done": "Done! Restart Claude Code to see your new pet.",
        "apply_cancelled": "Cancelled.",
        "bye": "Bye!",
        "error": "Error",
        "cmd_pick": "Custom pick mode (choose species/rarity/eyes/hat)",
        "pick_title": "Custom Pick Mode",
        "pick_species": "Choose species",
        "pick_rarity": "Choose rarity",
        "pick_eyes": "Choose eyes",
        "pick_hat": "Choose hat",
        "pick_shiny": "Shiny? [y/N]",
        "pick_preview": "Your custom pet",
        "pick_confirm": "Apply this pet to Claude Code? [y/N]",
        "pick_no_hat": "Common rarity = no hat",
        # Stats
        "DEBUGGING": "DEBUGGING",
        "PATIENCE": "PATIENCE",
        "CHAOS": "CHAOS",
        "WISDOM": "WISDOM",
        "SNARK": "SNARK",
        # Rarity
        "common": "Common",
        "uncommon": "Uncommon",
        "rare": "Rare",
        "epic": "Epic",
        "legendary": "Legendary",
    },
    "zh": {
        "banner_title": "ClaudePetRebirth",
        "banner_sub": "重新抽取你的 Claude Code 寵物!",
        "roll": "第",
        "rarity": "稀有度",
        "eyes": "眼睛",
        "hat": "帽子",
        "stats": "屬性",
        "commands": "操作說明",
        "cmd_reroll": "重新抽取",
        "cmd_keep": "收藏此寵物",
        "cmd_favs": "查看收藏",
        "cmd_remove": "移除最後一個收藏",
        "cmd_save": "儲存收藏到檔案",
        "cmd_anim": "開關動畫預覽",
        "cmd_help": "顯示說明",
        "cmd_lang": "切換語言",
        "cmd_quit": "離開",
        "no_favs": "還沒有收藏! 按 [k] 收藏寵物。",
        "favs_title": "收藏列表",
        "fav_apply": "套用該寵物到 Claude Code",
        "fav_remove": "移除最後一個收藏",
        "fav_back": "返回",
        "fav_invalid": "無效編號，請輸入",
        "kept": "已收藏",
        "favs_total": "個收藏",
        "removed": "已移除",
        "from_favs": "",
        "no_favs_remove": "沒有收藏可以移除。",
        "saved": "已儲存",
        "favs_to": "個收藏到",
        "no_favs_save": "沒有收藏可以儲存。",
        "anim": "動畫",
        "press_enter": "按 Enter 繼續...",
        "apply_title": "正在套用寵物到 Claude Code",
        "apply_target": "目標",
        "apply_searching": "搜尋匹配的 salt 中...",
        "apply_found": "找到了! 共",
        "apply_attempts": "次嘗試",
        "apply_patched": "修補完成!",
        "apply_replacements": "處替換, 驗證",
        "apply_backup": "備份",
        "apply_patch_failed": "修補失敗",
        "apply_confirm": "套用此寵物到 Claude Code? [y/N]",
        "apply_name": "幫你的{species}取個名字",
        "apply_set": "夥伴已設定",
        "apply_personality": "個性",
        "apply_done": "完成! 重啟 Claude Code 即可看到新寵物。",
        "apply_cancelled": "已取消。",
        "bye": "掰掰!",
        "error": "錯誤",
        "cmd_pick": "自選模式 (選擇物種/稀有度/眼睛/帽子)",
        "pick_title": "自選模式",
        "pick_species": "選擇物種",
        "pick_rarity": "選擇稀有度",
        "pick_eyes": "選擇眼睛",
        "pick_hat": "選擇帽子",
        "pick_shiny": "閃光? [y/N]",
        "pick_preview": "你的寵物",
        "pick_confirm": "套用此寵物到 Claude Code? [y/N]",
        "pick_no_hat": "普通稀有度 = 沒有帽子",
        # Stats
        "DEBUGGING": "除錯力",
        "PATIENCE": "耐心",
        "CHAOS": "混沌",
        "WISDOM": "智慧",
        "SNARK": "嘴砲",
        # Rarity
        "common": "普通",
        "uncommon": "非凡",
        "rare": "稀有",
        "epic": "史詩",
        "legendary": "傳說",
    },
}

SPECIES_ZH = {
    "duck": "鴨子", "goose": "鵝", "blob": "果凍", "cat": "貓",
    "dragon": "龍", "octopus": "章魚", "owl": "貓頭鷹", "penguin": "企鵝",
    "turtle": "烏龜", "snail": "蝸牛", "ghost": "幽靈", "axolotl": "六角恐龍",
    "capybara": "水豚", "cactus": "仙人掌", "robot": "機器人", "rabbit": "兔子",
    "mushroom": "蘑菇", "chonk": "胖胖",
}

current_lang = "en"


def set_lang(lang_code):
    global current_lang
    current_lang = lang_code


def t(key):
    return LANG[current_lang].get(key, key)


def species_name(species):
    if current_lang == "zh":
        return f"{species} ({SPECIES_ZH.get(species, species)})"
    return species
